<?php

use Phan\Issue;

/**
 * This configuration file was automatically generated by 'phan --init --init-level=3'
 *
 * @see https://github.com/phan/phan/wiki/Phan-Config-Settings for all configurable options
 * @see https://github.com/phan/phan/tree/v5/src/Phan/Config.php
 */
return [

    // The PHP version that the codebase will be checked for compatibility against.
    // Automatically inferred from composer.json requirement for "php" of ">=8.1"
    'target_php_version' => '8.1',

    // If enabled, missing properties will be created when
    // they are first seen. If false, we'll report an
    // error message if there is an attempt to write
    // to a class property that wasn't explicitly
    // defined.
    'allow_missing_properties' => false,

    // If enabled, null can be cast to any type and any
    // type can be cast to null. Setting this to true
    // will cut down on false positives.
    'null_casts_as_any_type' => false,

    // If enabled, allow null to be cast as any array-like type.
    'null_casts_as_array' => true,

    // If enabled, allow any array-like type to be cast to null.
    'array_casts_as_null' => true,

    // If enabled, scalars (int, float, bool, string, null)
    // are treated as if they can cast to each other.
    'scalar_implicit_cast' => false,

    // If enabled, any scalar array keys (int, string)
    // are treated as if they can cast to each other.
    'scalar_array_key_cast' => true,

    // If this has entries, scalars (int, float, bool, string, null)
    // are allowed to perform the casts listed.
    'scalar_implicit_partial' => [],

    // If enabled, Phan will warn if **any** type in a method invocation's object
    // is definitely not an object,
    // or if **any** type in an invoked expression is not a callable.
    'strict_method_checking' => false,

    // If enabled, Phan will warn if **any** type of the object expression for a property access
    // does not contain that property.
    'strict_object_checking' => false,

    // If enabled, Phan will warn if **any** type in the argument's union type
    // cannot be cast to a type in the parameter's expected union type.
    'strict_param_checking' => false,

    // If enabled, Phan will warn if **any** type in a property assignment's union type
    // cannot be cast to a type in the property's declared union type.
    'strict_property_checking' => false,

    // If enabled, Phan will warn if **any** type in a returned value's union type
    // cannot be cast to the declared return type.
    'strict_return_checking' => false,

    // If true, seemingly undeclared variables in the global
    // scope will be ignored.
    'ignore_undeclared_variables_in_global_scope' => true,

    // Set this to false to emit `PhanUndeclaredFunction` issues for internal functions that Phan has signatures for,
    // but aren't available in the codebase, or from Reflection.
    'ignore_undeclared_functions_with_known_signatures' => true,

    // Backwards Compatibility Checking.
    'backward_compatibility_checks' => false,

    // If true, check to make sure the return type declared
    // in the doc-block (if any) matches the return type
    // declared in the method signature.
    'check_docblock_signature_return_type_match' => false,

    // This setting maps case-insensitive strings to union types.
    'phpdoc_type_mapping' => [],

    // Set to true in order to attempt to detect dead
    // (unreferenced) code.
    'dead_code_detection' => false,

    // Set to true in order to attempt to detect unused variables.
    'unused_variable_detection' => false,

    // Set to true in order to attempt to detect redundant and impossible conditions.
    'redundant_condition_detection' => false,

    // If enabled, Phan will act as though it's certain of real return types of a subset of internal functions.
    'assume_real_types_for_internal_functions' => false,

    // If true, this runs a quick version of checks that takes less
    // time at the cost of not running as thorough
    // of an analysis.
    'quick_mode' => false,

    // Override to hardcode existence and types of (non-builtin) globals in the global scope.
    'globals_type_map' => [],

    // The minimum severity level to report on.
    'minimum_severity' => Issue::SEVERITY_LOW,

    // Add any issue types to this list to inhibit them from being reported.
    'suppress_issue_types' => [
        'PhanDeprecatedClass',
        'PhanDeprecatedFunction',
        'PhanTypeMismatchArgument',
        'PhanTypeMismatchArgumentReal',
        'PhanTypeArraySuspiciousNullable',
        'PhanTypePossiblyInvalidDimOffset',
        'PhanTypeMismatchArgumentNullableInternal',
        'PhanTypeMismatchArgumentInternalProbablyReal',
        'PhanTypeInvalidThrowsIsInterface',
        'PhanTypeMismatchArgumentSuperType',
        'PhanMissingRequireFile',
    ],

    // A regular expression to match files to be excluded
    // from parsing and analysis and will not be read at all.
    'exclude_file_regex' => '@^vendor/.*/(tests?|Tests?)/@',

    // A list of files that will be excluded from parsing and analysis
    // and will not be read at all.
    'exclude_file_list' => [],

    // A directory list that defines files that will be excluded
    // from static analysis, but whose class and method
    // information should be included.
    'exclude_analysis_directory_list' => [
        'vendor/',
        'tests/',
    ],

    // Enable this to enable checks of require/include statements referring to valid paths.
    'enable_include_path_checks' => true,

    // The number of processes to fork off during the analysis phase.
    'processes' => 1,

    // List of case-insensitive file extensions supported by Phan.
    'analyzed_file_extensions' => [
        'php',
    ],

    // You can put paths to stubs of internal extensions in this config option.
    'autoload_internal_extension_signatures' => [],

    // A list of plugin files to execute.
    'plugins' => [
        'AlwaysReturnPlugin',
        'PregRegexCheckerPlugin',
        'UnreachableCodePlugin',
    ],

    // A list of directories that should be parsed for class and
    // method information.
    'directory_list' => [
        'addons',
        'config',
        'inc',
        'install',
        'lib',
        'tests',
        'vendor',
    ],

    // A list of individual files to include in analysis
    // with a path relative to the root directory of the
    // project.
    'file_list' => [
        'index.php',
        'dynamic_update.php',
    ],
];
