<?php

namespace unit;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Poweradmin\Domain\Model\RecordComment;

#[CoversClass(RecordComment::class)]
class RecordCommentTest extends TestCase
{
    #[Test]
    public function constructorSetsAllFields(): void
    {
        $comment = new RecordComment(1, 10, 'example.com', 'A', 1700000000, 'admin', 'Test comment');

        $this->assertSame(1, $comment->getId());
        $this->assertSame(10, $comment->getDomainId());
        $this->assertSame('example.com', $comment->getName());
        $this->assertSame('A', $comment->getType());
        $this->assertSame(1700000000, $comment->getModifiedAt());
        $this->assertSame('admin', $comment->getAccount());
        $this->assertSame('Test comment', $comment->getComment());
    }

    #[Test]
    public function constructorWithNullAccount(): void
    {
        $comment = new RecordComment(2, 10, 'example.com', 'MX', 1700000000, null, 'No account');

        $this->assertNull($comment->getAccount());
    }

    #[Test]
    public function createFactoryWithAutoGeneratedModifiedAt(): void
    {
        $before = time();
        $comment = RecordComment::create(5, 'test.example.com', 'AAAA', 'IPv6 record', 'admin');
        $after = time();

        $this->assertNull($comment->getId());
        $this->assertSame(5, $comment->getDomainId());
        $this->assertSame('test.example.com', $comment->getName());
        $this->assertSame('AAAA', $comment->getType());
        $this->assertSame('IPv6 record', $comment->getComment());
        $this->assertSame('admin', $comment->getAccount());
        $this->assertGreaterThanOrEqual($before, $comment->getModifiedAt());
        $this->assertLessThanOrEqual($after, $comment->getModifiedAt());
    }

    #[Test]
    public function createFactoryWithNullAccount(): void
    {
        $comment = RecordComment::create(5, 'test.example.com', 'A', 'A record');

        $this->assertNull($comment->getAccount());
    }

    #[Test]
    public function updateReturnsNewInstance(): void
    {
        $original = new RecordComment(1, 10, 'example.com', 'A', 1700000000, 'admin', 'Original');

        $updated = $original->update('new.example.com', 'AAAA', 'Updated comment', 'manager');

        $this->assertNotSame($original, $updated);
        $this->assertSame(1, $updated->getId());
        $this->assertSame(10, $updated->getDomainId());
        $this->assertSame('new.example.com', $updated->getName());
        $this->assertSame('AAAA', $updated->getType());
        $this->assertSame('Updated comment', $updated->getComment());
        $this->assertSame('manager', $updated->getAccount());
    }

    #[Test]
    public function updateSetsNewModifiedAt(): void
    {
        $original = new RecordComment(1, 10, 'example.com', 'A', 1600000000, 'admin', 'Original');

        $before = time();
        $updated = $original->update(null, null, 'Changed');
        $after = time();

        $this->assertGreaterThanOrEqual($before, $updated->getModifiedAt());
        $this->assertLessThanOrEqual($after, $updated->getModifiedAt());
        $this->assertNotSame(1600000000, $updated->getModifiedAt());
    }

    #[Test]
    public function updateWithNullParamsKeepsOriginalValues(): void
    {
        $original = new RecordComment(1, 10, 'example.com', 'A', 1700000000, 'admin', 'Keep this');

        $updated = $original->update(null, null, null, null);

        $this->assertSame('example.com', $updated->getName());
        $this->assertSame('A', $updated->getType());
        $this->assertSame('Keep this', $updated->getComment());
        $this->assertSame('admin', $updated->getAccount());
    }

    #[Test]
    public function originalUnchangedAfterUpdate(): void
    {
        $original = new RecordComment(1, 10, 'example.com', 'A', 1700000000, 'admin', 'Original');

        $original->update('changed.example.com', 'CNAME', 'Changed', 'manager');

        $this->assertSame('example.com', $original->getName());
        $this->assertSame('A', $original->getType());
        $this->assertSame('Original', $original->getComment());
        $this->assertSame('admin', $original->getAccount());
        $this->assertSame(1700000000, $original->getModifiedAt());
    }
}
