name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issue or PR
        uses: pozil/auto-assign-issue@21ffb634481e75f2557e5f507e359cba97bbc42b # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: edmondas
          numOfAssignee: 1
          abortIfPreviousAssignees: false
